import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"

import './globals.css'
import Navbar from './components/layout/navbar'
import Footer from './components/layout/footer'

export const metadata = {
  title: 'Jake Lipson',
  // description: 'Generated by create next app.',
  openGraph: {
    title: 'Jake Lipson',
    url: 'https://jakelipson.com',
    siteName: 'Jake Lipson',
    images: [
      {
        url: '/images/opengraph/opengraph-image.png',
        width: 1280,
        height: 1280,
      }
    ],
    locale: 'en-us',
    type: 'website',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-dark text-secondary'>
        <Navbar />
        {children}
        <Footer />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
