import './globals.css'
import Navbar from './components/layout/navbar'
import Footer from './components/layout/footer'

export const metadata = {
  title: 'Jake Lipson',
  description: 'Generated by create next app.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-primary text-secondary'>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
